apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-app
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: 977099014013.dkr.ecr.us-east-1.amazonaws.com/wiz-tasky-repository:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://tasky_admin:SecurePassword12453@10.0.1.127:27017/tasky?authSource=admin"
        - name: SECRET_KEY
          value: "WizLabSecret"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080