name: "Build, Scan & Push App"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend-app/**'  # Only run if files in this folder change
  workflow_dispatch: # This lets you trigger it manually for testing

jobs:
  build-and-scan:
    name: "Build & Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          # Build the image inside the correct folder
          docker build -t tasky-backend:${{ github.sha }} ./backend-app

      - name: Run Trivy Vulnerability Scanner
        run: |
          # We run Trivy as a container to avoid the Git Fetch error
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image --exit-code 0 --severity CRITICAL,HIGH tasky-backend:${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wiz-tasky-repo 
        run: |
          docker tag tasky-backend:${{ github.sha }} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend-app
          platforms: linux/amd64  # Explicitly target EKS node architecture
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/wiz-tasky-repo:latest
            ${{ steps.login-ecr.outputs.registry }}/wiz-tasky-repo:${{ github.sha }}